import 'package:russian_declinator/services/databases/database.dart' show Adjective, Noun;

class TestInstances {
  TestInstances._();

  static Adjective adjective({
    int id = 0,
    String bare = '',
    String accented = '',
    String translationsEN = '',
    String translationsDE = '',
    String mNom = 'mNom',
    String mGen = 'mGen',
    String mDat = 'mDat',
    String mAcc = 'mAcc',
    String mInst = 'mInst',
    String mPrep = 'mPrep',
    String fNom = 'fNom',
    String fGen = 'fGen',
    String fDat = 'fDat',
    String fAcc = 'fAcc',
    String fInst = 'fInst',
    String fPrep = 'fPrep',
    String nNom = 'nNom',
    String nGen = 'nGen',
    String nDat = 'nDat',
    String nAcc = 'nAcc',
    String nInst = 'nInst',
    String nPrep = 'nPrep',
    String plNom = 'plNom',
    String plGen = 'plGen',
    String plDat = 'plDat',
    String plAcc = 'plAcc',
    String plInst = 'plInst',
    String plPrep = 'plPrep',
  }) =>
      Adjective(
        id: id,
        bare: bare,
        accented: accented,
        translationsEN: translationsEN,
        translationsDE: translationsDE,
        mNom: mNom,
        mGen: mGen,
        mDat: mDat,
        mAcc: mAcc,
        mInst: mInst,
        mPrep: mPrep,
        fNom: fNom,
        fGen: fGen,
        fDat: fDat,
        fAcc: fAcc,
        fInst: fInst,
        fPrep: fPrep,
        nNom: nNom,
        nGen: nGen,
        nDat: nDat,
        nAcc: nAcc,
        nInst: nInst,
        nPrep: nPrep,
        plNom: plNom,
        plGen: plGen,
        plDat: plDat,
        plAcc: plAcc,
        plInst: plInst,
        plPrep: plPrep,
      );

  static Noun noun({
    int id = 0,
    String bare = '',
    String accented = '',
    String translationsEN = '',
    String translationsDE = '',
    bool isPlural = false,
    bool isSingular = false,
    bool isIndeclinable = false,
    bool isAnimate = false,
    String sgNom = 'sgNom',
    String sgGen = 'sgGen',
    String sgDat = 'sgDat',
    String sgAcc = 'sgAcc',
    String sgInst = 'sgInst',
    String sgPrep = 'sgPrep',
    String plNom = 'plNom',
    String plGen = 'plGen',
    String plDat = 'plDat',
    String plAcc = 'plAcc',
    String plInst = 'plInst',
    String plPrep = 'plPrep',
  }) =>
      Noun(
        id: id,
        bare: bare,
        accented: accented,
        translationsEN: translationsEN,
        translationsDE: translationsDE,
        isPlural: isPlural,
        isSingular: isSingular,
        isIndeclinable: isIndeclinable,
        isAnimate: isAnimate,
        sgNom: sgNom,
        sgGen: sgGen,
        sgDat: sgDat,
        sgAcc: sgAcc,
        sgInst: sgInst,
        sgPrep: sgPrep,
        plNom: plNom,
        plGen: plGen,
        plDat: plDat,
        plAcc: plAcc,
        plInst: plInst,
        plPrep: plPrep,
      );
}
