name: ci_pull_request
on: pull_request
jobs:
  lint-unit-test:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Install packages
        run: flutter pub get
      - name: Generate db
        run: |
          dart bin/db/download_dev_assets.dart
          dart bin/db/create_db.dart
      - name: Lint
        run: flutter analyze
      - name: Unit tests
        run: flutter test
  build-macOS:
    name: Build macOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Enable macOS Support
        run: flutter config --enable-macos-desktop
      - name: Generate db
        run: |
          dart bin/db/download_dev_assets.dart
          dart bin/db/create_db.dart
      - name: Build app
        run: flutter build macos --release
  build-iOS:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate db
        run: |
          dart bin/db/download_dev_assets.dart
          dart bin/db/create_db.dart
      - name: Build app
        run: flutter build ios --release --no-codesign
  build-Android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate db
        run: |
          dart bin/db/download_dev_assets.dart
          dart bin/db/create_db.dart
      - name: Build app
        run: flutter build appbundle --release
  build-Web:
    name: Build Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Generate db
        run: |
          dart bin/db/download_dev_assets.dart
          dart bin/db/create_db.dart
      - name: Build app
        run: flutter build web --release
